# Generated by Django 3.2.7 on 2021-10-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(help_text='Check this box if you want the images to render in the featured work carousel.'),
        ),
    ]
